services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    TorqNorth\DataImporterExtensionsBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']


    TorqNorth\DataImporterExtensionsBundle\Resolver\Load\AdvancedPathStrategy:
        tags:
            - { name: "pimcore.datahub.data_importer.resolver.load", type: "advancedPath" }

    TorqNorth\DataImporterExtensionsBundle\Resolver\Load\PropertyStrategy:
        tags:
            - { name: "pimcore.datahub.data_importer.resolver.load", type: "property" }

    TorqNorth\DataImporterExtensionsBundle\Resolver\Location\AdvancedParentStrategy:
        tags:
            - { name: "pimcore.datahub.data_importer.resolver.location", type: "advancedParent" }

    TorqNorth\DataImporterExtensionsBundle\DataSource\Interpreter\AdvancedXlsxFileInterpreter:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: 'DATA-IMPORTER' }
            - { name: "pimcore.datahub.data_importer.interpreter", type: "advancedXlsx" }

    TorqNorth\DataImporterExtensionsBundle\DataSource\Interpreter\BulkXlsxFileInterpreter:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: 'DATA-IMPORTER' }
            - { name: "pimcore.datahub.data_importer.interpreter", type: "bulkXlsx" }

    TorqNorth\DataImporterExtensionsBundle\DataSource\Interpreter\XMLSchemaBasedPreview:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: 'DATA-IMPORTER' }
            - { name: "pimcore.datahub.data_importer.interpreter", type: "XMLSchemaBasedPreview" }

    TorqNorth\DataImporterExtensionsBundle\DataSource\Interpreter\BulkCsvFileInterpreter:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: 'DATA-IMPORTER' }
            - { name: "pimcore.datahub.data_importer.interpreter", type: "bulkCsv" }

    TorqNorth\DataImporterExtensionsBundle\DataSource\Interpreter\SqlFileInterpreter:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: 'DATA-IMPORTER' }
            - { name: "pimcore.datahub.data_importer.interpreter", type: "sql" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\Operator\Simple\SafeKey:
        tags:
            - { name: "pimcore.datahub.data_importer.operator", type: "safeKey" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\Operator\Simple\Constant:
        tags:
            - { name: "pimcore.datahub.data_importer.operator", type: "constant" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\Operator\Simple\Arithmetic:
        tags:
            - { name: "pimcore.datahub.data_importer.operator", type: "arithmetic" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\Operator\Simple\RegexReplace:
        tags:
            - { name: "pimcore.datahub.data_importer.operator", type: "regexReplace" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\DataTarget\Property:
        tags:
            - { name: "pimcore.datahub.data_importer.data_target", type: "property" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\DataTarget\AdvancedClassificationStore:
        tags:
            - { name: "pimcore.datahub.data_importer.data_target", type: "advancedClassificationStore" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\Operator\Simple\ImportAssetAdvanced:
        tags:
            - { name: "pimcore.datahub.data_importer.operator", type: "importAssetAdvanced" }

    TorqNorth\DataImporterExtensionsBundle\Mapping\DataTarget\ImageGalleryAppender:
        tags:
            - { name: "pimcore.datahub.data_importer.data_target", type: "imageGalleryAppender" }

    TorqNorth\DataImporterExtensionsBundle\DataSource\Loader\SqlDataLoader:
        tags:
            - { name: "pimcore.datahub.data_importer.loader", type: "sql" }


# add more services, or override services that need manual wiring
#    TorqNorth\DataImporterExtensionsBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
